### PR TITLE
TTY support

### PR DESCRIPTION
**Pull request by justinbloomfield**
Created a template for console colours, and added a section in the executable to fix the output if using TTY template

### CODE REVIEW

**Comment by tudurom** [comment]
i'll merge it after you fix the spacing in the template file (`gg=G` in vim). other than that, if it works, i'll merge it. i cannot test it because i use freebsd. you can also rename `tty` to `linux_tty`.

**Comment by justinbloomfield** [comment]
Alright, no spacing in the template (thanks for that command), and renamed to linux_tty. Should be okay now.

**Comment by tudurom** [comment]
AAAW YEEEAH thanks!

**Comment by tudurom** [comment]
i love your colors

**Comment by justinbloomfield** [comment]
thanks for merging! 
ah, thanks. They were from my old Chernobyl setup, but now that I'm running mostly without X i thought i'd revive them. Your Cloudy was the original scheme on that one though, believe it or not.

**Pull request merged**
